
/**
* ChatClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class ChatClient implements org.omg.CORBA.portable.IDLEntity
{
  public long clientID = (long)0;
  public String currentRoom = null;
  public long friendList[] = null;
  public Listener listener = null;

  public ChatClient ()
  {
  } // ctor

  public ChatClient (long _clientID, String _currentRoom, long[] _friendList, Listener _listener)
  {
    clientID = _clientID;
    currentRoom = _currentRoom;
    friendList = _friendList;
    listener = _listener;
  } // ctor

} // class ChatClient
