
/**
* ChatRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class ChatRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatRoom value = null;

  public ChatRoomHolder ()
  {
  }

  public ChatRoomHolder (ChatRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatRoomHelper.type ();
  }

}
