
/**
* ChatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatClientHelper.type ();
  }

}
