
/**
* ChatClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

abstract public class ChatClientHelper
{
  private static String  _id = "IDL:ChatClient:1.0";

  public static void insert (org.omg.CORBA.Any a, ChatClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ChatClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "clientID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "currentRoom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (50, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FriendListHelper.id (), "FriendList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "friendList",
            _tcOf_members0,
            null);
          _tcOf_members0 = ListenerHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "listener",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ChatClientHelper.id (), "ChatClient", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ChatClient read (org.omg.CORBA.portable.InputStream istream)
  {
    ChatClient value = new ChatClient ();
    value.clientID = istream.read_longlong ();
    value.currentRoom = istream.read_string ();
    value.friendList = FriendListHelper.read (istream);
    value.listener = ListenerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ChatClient value)
  {
    ostream.write_longlong (value.clientID);
    ostream.write_string (value.currentRoom);
    FriendListHelper.write (ostream, value.friendList);
    ListenerHelper.write (ostream, value.listener);
  }

}
