
/**
* ChatRoomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

abstract public class ChatRoomHelper
{
  private static String  _id = "IDL:ChatRoom:1.0";

  public static void insert (org.omg.CORBA.Any a, ChatRoom that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ChatRoom extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ChatRoomHelper.id (), "ChatRoom");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ChatRoom read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ChatRoomStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ChatRoom value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ChatRoom narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatRoom)
      return (ChatRoom)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ChatRoomStub stub = new _ChatRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ChatRoom unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatRoom)
      return (ChatRoom)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ChatRoomStub stub = new _ChatRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
