
/**
* ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public interface ChatServerOperations 
{
  int addClientID ();
  ChatRoom createRoom (Room newroom) throws ChatServerPackage.LimitRoomsException;
  ChatRoom[] getRooms ();
  long getNumberOfRooms ();
  void setCurrentRoom (long clientID, String currentRoom);
  void enterRoom (String roomName, long clientID);
  long getNumberOfClientsInRoom (long clientID);
  void leaveRoom (long clientID);
  ChatClient registerClient (ChatClient newClient) throws ChatServerPackage.LimitClientsException;
  boolean authenticate (String password);
  void previousMsg (long clientID);
  void receiveMsg (String userName, long clientId, String msg);
  void exit (long clientID);
} // interface ChatServerOperations
