
/**
* ClientsRoomListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

abstract public class ClientsRoomListHelper
{
  private static String  _id = "IDL:ClientsRoomList:1.0";

  public static void insert (org.omg.CORBA.Any a, long[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static long[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (50, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ClientsRoomListHelper.id (), "ClientsRoomList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static long[] read (org.omg.CORBA.portable.InputStream istream)
  {
    long value[] = null;
    int _len0 = istream.read_long ();
    if (_len0 > (50))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value = new long[_len0];
    istream.read_longlong_array (value, 0, _len0);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, long[] value)
  {
    if (value.length > (50))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_long (value.length);
    ostream.write_longlong_array (value, 0, value.length);
  }

}
