
/**
* ClientsRoomListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class ClientsRoomListHolder implements org.omg.CORBA.portable.Streamable
{
  public long value[] = null;

  public ClientsRoomListHolder ()
  {
  }

  public ClientsRoomListHolder (long[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientsRoomListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientsRoomListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientsRoomListHelper.type ();
  }

}
