
/**
* ListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public abstract class ListenerPOA extends org.omg.PortableServer.Servant
 implements ListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getUserName", new java.lang.Integer (0));
    _methods.put ("setUserName", new java.lang.Integer (1));
    _methods.put ("getAuthenticated", new java.lang.Integer (2));
    _methods.put ("setAuthenticated", new java.lang.Integer (3));
    _methods.put ("getClientId", new java.lang.Integer (4));
    _methods.put ("message", new java.lang.Integer (5));
    _methods.put ("recievePreviousMsg", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Listener/getUserName
       {
         String $result = null;
         $result = this.getUserName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Listener/setUserName
       {
         String userName = in.read_string ();
         this.setUserName (userName);
         out = $rh.createReply();
         break;
       }

       case 2:  // Listener/getAuthenticated
       {
         boolean $result = false;
         $result = this.getAuthenticated ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Listener/setAuthenticated
       {
         boolean status = in.read_boolean ();
         this.setAuthenticated (status);
         out = $rh.createReply();
         break;
       }

       case 4:  // Listener/getClientId
       {
         long $result = (long)0;
         $result = this.getClientId ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 5:  // Listener/message
       {
         String userName = in.read_string ();
         String msg = in.read_string ();
         this.message (userName, msg);
         out = $rh.createReply();
         break;
       }

       case 6:  // Listener/recievePreviousMsg
       {
         String msg = in.read_string ();
         this.recievePreviousMsg (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Listener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Listener _this() 
  {
    return ListenerHelper.narrow(
    super._this_object());
  }

  public Listener _this(org.omg.CORBA.ORB orb) 
  {
    return ListenerHelper.narrow(
    super._this_object(orb));
  }


} // class ListenerPOA
