
/**
* ListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public interface ListenerOperations 
{
  String getUserName ();
  void setUserName (String userName);
  boolean getAuthenticated ();
  void setAuthenticated (boolean status);
  long getClientId ();
  void message (String userName, String msg);
  void recievePreviousMsg (String msg);
} // interface ListenerOperations
