
/**
* Room.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class Room implements org.omg.CORBA.portable.IDLEntity
{
  public String roomName = null;
  public long clientsRoomList[] = null;
  public int clientsJoined = (int)0;
  public int roomIndex = (int)0;

  public Room ()
  {
  } // ctor

  public Room (String _roomName, long[] _clientsRoomList, int _clientsJoined, int _roomIndex)
  {
    roomName = _roomName;
    clientsRoomList = _clientsRoomList;
    clientsJoined = _clientsJoined;
    roomIndex = _roomIndex;
  } // ctor

} // class Room
