
/**
* RoomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

abstract public class RoomHelper
{
  private static String  _id = "IDL:Room:1.0";

  public static void insert (org.omg.CORBA.Any a, Room that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Room extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "roomName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (50, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ClientsRoomListHelper.id (), "ClientsRoomList", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "clientsRoomList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "clientsJoined",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "roomIndex",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RoomHelper.id (), "Room", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Room read (org.omg.CORBA.portable.InputStream istream)
  {
    Room value = new Room ();
    value.roomName = istream.read_string ();
    value.clientsRoomList = ClientsRoomListHelper.read (istream);
    value.clientsJoined = istream.read_long ();
    value.roomIndex = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Room value)
  {
    ostream.write_string (value.roomName);
    ClientsRoomListHelper.write (ostream, value.clientsRoomList);
    ostream.write_long (value.clientsJoined);
    ostream.write_long (value.roomIndex);
  }

}
