
/**
* RoomListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class RoomListHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatRoom value[] = null;

  public RoomListHolder ()
  {
  }

  public RoomListHolder (ChatRoom[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoomListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoomListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoomListHelper.type ();
  }

}
