package ChatServerPackage;

/**
* ChatServerPackage/LimitRoomsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class LimitRoomsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatServerPackage.LimitRoomsException value = null;

  public LimitRoomsExceptionHolder ()
  {
  }

  public LimitRoomsExceptionHolder (ChatServerPackage.LimitRoomsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatServerPackage.LimitRoomsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatServerPackage.LimitRoomsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatServerPackage.LimitRoomsExceptionHelper.type ();
  }

}
