package ChatServerPackage;


/**
* ChatServerPackage/LimitClientsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class LimitClientsException extends org.omg.CORBA.UserException
{

  public LimitClientsException ()
  {
    super(LimitClientsExceptionHelper.id());
  } // ctor


  public LimitClientsException (String $reason)
  {
    super(LimitClientsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class LimitClientsException
