package ChatServerPackage;


/**
* ChatServerPackage/LimitRoomsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class LimitRoomsException extends org.omg.CORBA.UserException
{

  public LimitRoomsException ()
  {
    super(LimitRoomsExceptionHelper.id());
  } // ctor


  public LimitRoomsException (String $reason)
  {
    super(LimitRoomsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class LimitRoomsException
