package ChatServerPackage;

/**
* ChatServerPackage/LimitClientsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatIDL.idl
* Sunday, December 3, 2017 7:42:28 PM BRT
*/

public final class LimitClientsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatServerPackage.LimitClientsException value = null;

  public LimitClientsExceptionHolder ()
  {
  }

  public LimitClientsExceptionHolder (ChatServerPackage.LimitClientsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatServerPackage.LimitClientsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatServerPackage.LimitClientsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatServerPackage.LimitClientsExceptionHelper.type ();
  }

}
