module ChatInterface {
    interface ChatClient {
        void refresh(in string name, in string text);
    };
    exception NameAlreadyExists {};
    exception UnknownID {};

    interface ChatServer {
        string subscribe(in string nick, in ChatClient c) raises (NameAlreadyExists);
        void unsubscribe(in string id) raises (UnknownID);
        void send(in string id, in string text) raises (UnknownID);
    };
};