package ChatInterface;


/**
* ChatInterface/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public interface ChatServerOperations 
{
  String subscribe (String nick, ChatInterface.ChatClient c) throws ChatInterface.NameAlreadyExists;
  void unsubscribe (String id) throws ChatInterface.UnknownID;
  void send (String id, String text) throws ChatInterface.UnknownID;
} // interface ChatServerOperations
