package ChatInterface;


/**
* ChatInterface/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public interface ChatClientOperations 
{
  void refresh (String name, String text);
} // interface ChatClientOperations
