package ChatInterface;

/**
* ChatInterface/ChatServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public final class ChatServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatInterface.ChatServer value = null;

  public ChatServerHolder ()
  {
  }

  public ChatServerHolder (ChatInterface.ChatServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatInterface.ChatServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatInterface.ChatServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatInterface.ChatServerHelper.type ();
  }

}
