package ChatInterface;

/**
* ChatInterface/ChatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatInterface.ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (ChatInterface.ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatInterface.ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatInterface.ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatInterface.ChatClientHelper.type ();
  }

}
