package ChatInterface;

/**
* ChatInterface/NameAlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public final class NameAlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatInterface.NameAlreadyExists value = null;

  public NameAlreadyExistsHolder ()
  {
  }

  public NameAlreadyExistsHolder (ChatInterface.NameAlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatInterface.NameAlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatInterface.NameAlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatInterface.NameAlreadyExistsHelper.type ();
  }

}
