package ChatInterface;


/**
* ChatInterface/UnknownID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatInterface.idl
* Friday, December 1, 2017 12:01:21 AM BRT
*/

public final class UnknownID extends org.omg.CORBA.UserException
{

  public UnknownID ()
  {
    super(UnknownIDHelper.id());
  } // ctor


  public UnknownID (String $reason)
  {
    super(UnknownIDHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownID
